[package]
name = "rew"
version = "1.0.0"
edition = "2024"

[dependencies]
bstr = "1.11.3"
memchr = "2.7.4"

[profile.release]
codegen-units = 1
panic = "abort"
strip = true
lto = true

[lints.clippy]
all = { level = "deny", priority = -1 }
pedantic = { level = "deny", priority = -1 }

[dev-dependencies]
claims = "0.8.0"
rstest = "0.25.0"
