[package]
name = "rew"
version = "1.0.0"
description = "The Swiss Army Knife of line-oriented text processing."
categories = ["command-line-utilities", "text-processing", "filesystem"]
keywords = ["cli", "utility", "text", "rename", "path"]
authors = ["Jan Pikl <pikl.jan@gmail.com>"]
repository = "https://github.com/jpikl/rew"
documentation = "https://jpikl.github.io/rew"
homepage = "https://jpikl.github.io/rew"
license = "MIT"
edition = "2024"

[dependencies]
anstream = "0.6.18"
anyhow = "1.0.97"
bstr = "1.11.3"
os_str_bytes = "7.1"

[profile.release]
codegen-units = 1
panic = "abort"
strip = true
lto = true

[lints.clippy]
all = { level = "deny", priority = -1 }

[dev-dependencies]
claims = "0.8.0"
rstest = "0.25.0"
temp-env = "0.3.6"
